{
 "title": "log_gen",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Log Lines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(promtail_custom_log_lines_total[5m]))",
     "legendFormat": "Log lines"
    }
   ]
  },
  {
   "title": "Log Lines by Level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "sum by (level) (rate(promtail_custom_log_lines_total{}[5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Events",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (rate(promtail_custom_log_lines_total[5m]))",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(promtail_custom_response_time_seconds_bucket[5m]))) ",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(promtail_custom_response_time_seconds_bucket[5m]))) ",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(promtail_custom_response_time_seconds_bucket[5m]))) ",
     "legendFormat": "P99"
    },
    {
     "expr": "sum(rate(promtail_custom_response_time_seconds_sum[5m])) / sum(rate(promtail_custom_response_time_seconds_count[5m]))",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "Login", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Attempts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "rate(promtail_custom_login_attempts_success_total[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(promtail_custom_login_attempts_failed_total[5m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Failure Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " scalar(rate(promtail_custom_login_attempts_failed_total[5m]))/ (scalar(rate(promtail_custom_login_attempts_success_total[5m])) + scalar(rate(promtail_custom_login_attempts_failed_total[5m])))",
     "legendFormat": "Failure Rate"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"demo_log\", action=\"LOGIN\"}"
    }
   ]
  }
 ]
}